### ISSUE TITLE
Error in 'LLM 01L - LLMs with Hugging Face Lab.py'

### ISSUE THREAD

**Issue by Keertiraj** [databricks-academy/large-language-models#2]
I get the below error, when i run the code in Jupyter Notebook:

Adding the below line of code solved the problem:

 

pip install -U accelerate and restart the notebook

[Here is the error discussion: https://github.com/huggingface/transformers/issues/23340](https://stackoverflow.com/questions/76225595/nameerror-name-partialstate-is-not-defined-error-while-training-hugging-face)

**Comment by brookewenig** [comment]
These notebooks are intended to be run solely in a Databricks environment. As such, I'll be closing this issue.
