### ISSUE TITLE
DA.reset_lesson() error

### ISSUE THREAD

**Issue by atsui2000** [databricks-academy/large-language-models#3]
When I run

%run ../Includes/Classroom-Setup

for the first time, and I received errors.  I looked inside the code, it was at the line "DA.reset_lesson()".  I was able to bypass this by commenting out this line, since it was the first time running the code, there's no need to reset anything.  But I think it may be helpful to provide the feedback.

**Comment by brookewenig** [comment]
I'm not able to reproduce this error (the reset_lesson() is intended to clean up the state of the notebook). I'll close for now, but will re-open if reported my others. Thanks for reporting!
