### ISSUE TITLE
Missing the "Releases" section for slides and pdf

### ISSUE THREAD

**Issue by spicoflorin** [databricks-academy/large-language-models#8]
Hello!

I could not find the "Releases" section in this repo for getting the slides of the course.
Can you please point out where can I find them?
 Thanks,
 Florin

**Comment by cdutr** [comment]
+1

**Comment by entrustgabri** [comment]
Couldn't find them either

**Comment by brookewenig** [comment]
It should be on the right hand side of the main repo. Are you able to access this page: https://github.com/databricks-academy/large-language-models/releases?

**Comment by cdutr** [comment]
In fact, it was there 😅 I was able to download the slides now. Thanks @brookewenig

**Comment by brookewenig** [comment]
Thanks for confirming! Closing this issue :)
